[client]
showErrorDetails = false

[server]
headless = true
port = 8501

[theme]
base = "light"
primaryColor = "#2d3748"
backgroundColor = "#f8fafc"
secondaryBackgroundColor = "#f1f5f9"
textColor = "#1a202c"
font = "sans serif"